name: SpamHammer
main: com.dumptruckman.spamhammer.SpamHammerPlugin
version: maven-version-number
author: dumptruckman
softdepend: [SpoutPlugin]

commands:
  spam:
    description: Base command for SpamHammer.
    usage: |
           /<command>
  spamunmute:
    description: Unmutes a player banned by SpamHammer.
    usage: |
           /<command> <playername>
           /<command> dumptruckman - unmutes dumptruckman if he was muted by SpamHammer.
  spamreset:
    description: Resets a player's SpamHammer punishment level.
    usage: |
           /<command> <playername>
           /<command> dumptruckman - Makes it like dumptruckman never spammed in the first place.
  